<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1571837409380" stop="1571837409416">
  <name>test011</name>
  <labels/>
  <test-cases>
    <test-case start="1571837409380" status="passed" stop="1571837409384">
      <name>Test02.test01</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="14776-MainThread"/>
        <label name="host" value="WIN-SEBC72BGI1D"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1571837409385" status="failed" stop="1571837409416">
      <name>Test02.test02</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test011.Test02 object at 0x0648AE90&gt;

    def test02(self):
&gt;       assert 0
E       assert 0

scripts\test011.py:6: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="14776-MainThread"/>
        <label name="host" value="WIN-SEBC72BGI1D"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
